### ISSUE TITLE
re: conflict with cursor lock

### ISSUE THREAD

**Issue by meta-androcto** [dairin0d/enhanced-3d-cursor#2]
hi, I really like your tools, I have a conflict issue currently with chromoly's lock cursor: 
https://github.com/chromoly/lock_cursor3d
lock does not work with your addon enabled.
this only occurs with enhanced-3d-cursor & not with your transform tools hide cursor.
I really would like these 2 addons to work well together.
Thanks for your great suite of addons, I'm still in irc freenode #blenderpython. :)
drop in for a chat.

**Comment by dairin0d** [comment]
Chromoly's lock_cursor3d addon replaces the default view3d.cursor3d operator with a custom implementation, whereas my enhanced_3d_cursor disables view3d.cursor3d in keymaps and registers a separate operator. This means that our addons cannot coexist by definition. However, I can add an option to lock cursor in my addon too, if necessary (though it's less of an issue, since the user can cancel the movement or return the cursor to a previous position).

**Comment by meta-androcto** [comment]
hi, I wonder if there's an overall nicer way to do this, could enhanced 3d cursor be mapped to alt/leftclick? or run modal per session & store the cursor data? what do you think?

**Comment by dairin0d** [comment]
Added Chromoly's lock_cursor3d functionality (cursor locking and snapping to circumscribed/inscribed circles).
